In [2]:
import numpy as np

In [3]:
#Get a specific element [r,c]
a =np.array([[1,2,3,4,5,6,7],[8,9,10,11,12,13,14]])
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14]]


In [4]:
a[1,5]

13

In [5]:
#Get a specific row
a[0:]

array([[ 1,  2,  3,  4,  5,  6,  7],
       [ 8,  9, 10, 11, 12, 13, 14]])

In [8]:
#Get a specific column
a[:, 2]

array([ 3, 10])

In [9]:
#Getting a little more fancy[Startindex:Endindex,stepsize]
a[0,1:6:2]

array([2, 4, 6])

In [10]:
a[1,5]=20
print(a)

[[ 1  2  3  4  5  6  7]
 [ 8  9 10 11 12 20 14]]


In [11]:
b=np.array([[[1,2],[3,4]],[[5,6],[7,8]]])
print(b)

[[[1 2]
  [3 4]]

 [[5 6]
  [7 8]]]


In [12]:
#Get a specific element
b[0,1,1]

4

In [14]:
#replace
b[:,1,:]=[[9,9],[8,8]]
b

array([[[1, 2],
        [9, 9]],

       [[5, 6],
        [8, 8]]])