# Arrays

In [4]:
import numpy as np  

In [5]:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [6]:
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [8]:
#All 1s matrix
np.ones((4,2,2), dtype='int32')

array([[[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]],

       [[1, 1],
        [1, 1]]])

In [10]:
#Any other number
np.full((2,2),99, dtype='float32')

array([[99., 99.],
       [99., 99.]], dtype=float32)

In [12]:
#Random numbers
np.random.rand(4,2,3)

array([[[0.98571086, 0.85772001, 0.96810351],
        [0.55797005, 0.38820122, 0.49913207]],

       [[0.5859223 , 0.25221021, 0.15219971],
        [0.14670562, 0.51488531, 0.28194851]],

       [[0.56700215, 0.26123569, 0.06042218],
        [0.41767539, 0.17246174, 0.68770231]],

       [[0.76932185, 0.69997266, 0.50685214],
        [0.49792049, 0.63764683, 0.84699143]]])

In [14]:
#Random Integer values
np.random.randint(-4,8,size=(3,3))

array([[-1, -4,  5],
       [-4,  1,  7],
       [ 0,  3,  4]])

In [16]:
np.identity(3)#Identity matrix

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [17]:
arr=np.array([1,2,3])
r1=np.repeat(arr,3)
print(r1) #One dimentional array

[1 1 1 2 2 2 3 3 3]


In [19]:
#Two dimentional array
arr1=np.array([[1,2,3]])
g=np.repeat(arr1,4,axis=0)
print(g)#Repeat an array

[[1 2 3]
 [1 2 3]
 [1 2 3]
 [1 2 3]]


In [26]:
output=np.ones((5,5))
print(output)

z=np.zeros((3,3))
z[1,1]=9
print(z)

output[1:-1,1:-1]=z
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


# Be careful while copying arrays


In [28]:
a=np.array([1,2,3])
b=a
b

array([1, 2, 3])

In [29]:
b[0]=100
print(b)

[100   2   3]


In [30]:
print(a) #This is a problem because the content of a is also automatically changing along with b

[100   2   3]


In [35]:
#Instead of = we use copy function to be safe
a=np.array([1,2,3])
b=a.copy()
b[1]=20
print(b)

[ 1 20  3]


In [36]:
print(a)

[1 2 3]
