In [1]:
import numpy as np

# Load data from a file

In [5]:
filedata=np.genfromtxt('data', delimiter=',')
filedata=filedata.astype('int32')
filedata

array([ 1,  2,  3,  4,  5,  6,  7, 89])

# Boolean Masking and Advance Indexing

In [6]:
filedata>50

array([False, False, False, False, False, False, False,  True])

In [9]:
filedata[filedata>50]

array([89])

In [11]:
((filedata>5) & (filedata<90))

array([False, False, False, False, False,  True,  True,  True])