# Load in NumPy(remember to install numpy first)

In [2]:
import numpy as np

# The Basics

In [3]:
a = np.array([1,2,4])
a

array([1, 2, 4])

In [4]:
print(a)

[1 2 4]


In [5]:
b= np.array([[1,5,8],[6.0,3.0,7.0]])
print(b)

[[1. 5. 8.]
 [6. 3. 7.]]


In [10]:
a.ndim
 #Get Dimension

1

In [8]:
a.shape # Get shape

(3,)

In [11]:
b.ndim

2

In [13]:
b.shape

(2, 3)

In [14]:
#Get Type
a.dtype

dtype('int32')

In [16]:
#Get Size
a.itemsize

4

In [19]:
#Get Total Size
#a.size * a.itemsize OR
a.nbytes

12